# -*- mode: ruby -*-
# vi: set ft=ruby :

VM_OS = "centos/7"
DOCKER_VERSION = "19.03.3"

cluster = {
  "kubemaster01" => { :ip => "172.28.128.10", :cpus=> 2, :mem=> 2096},
  "kubemaster02" => { :ip => "172.28.128.11", :cpus=> 2, :mem=> 2096},
  "kubemaster03" => { :ip => "172.28.128.12", :cpus=> 2, :mem=> 2096},
  "kubenode01" => { :ip => "172.28.128.13", :cpus=> 2, :mem=> 2096},
  "kubenode02" => { :ip => "172.28.128.14", :cpus=> 2, :mem=> 2096}
}

Vagrant.configure("2") do |config|

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.network "forwarded_port", guest: 80, host: 80, auto_correct: true
  config.vm.network "forwarded_port", guest: 443, host: 443, auto_correct: true

  cluster.each_with_index do |(hostname, info), index|
    config.vm.define hostname do |cfg|
      cfg.vm.provider :virtualbox do |vb, override|
        config.vm.box = VM_OS
        config.vm.box_check_update = false
        override.vm.network :private_network, ip: "#{info[:ip]}"
        override.vm.hostname = hostname
        vb.name = hostname
        vb.customize [ "modifyvm", :id, "--memory", info[:mem], "--cpus", info[:cpus], "--hwvirtex", "on"]  

        override.vm.provision "shell", inline: <<-SHELL
          yum -y update
          reboot
        SHELL
    
      end
    end
  end

end
