apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: frontend 
  name: pod-deployment-reader
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list"]
